library(tidyverse)

# https://github.com/nih-cfde/published-documentation/wiki/
# submission-prep-script  C2M2-Table-Summary Quickstart

# set working directory to source file location

# download blank files and save in "osfstorage-archive/"

dcc_id = "cfde_registry_dcc:test1"

id_namespace = "tag:raynamharris.com"
id_description = "Testing account for Rayna Harris"

id_name = "raynamharris"
id_abbreviation = "RMH"

contact_email = "rmharris@ucdavis.edu"
contact_name = "Rayna"

project_id_namespace = id_namespace
project_local_id = "PRJNA417316"


outdir = "rmh_2022_04_11/"


getcolnames <- function(file){
  tsvcolnames <- read_tsv(file) %>% 
    colnames()
  return(tsvcolnames)
}

dcc_cols <- getcolnames("osfstorage-archive/dcc.tsv")
dcc_cols

dcc.tsv <- data.frame(id = dcc_id,
                      dcc_name = id_name,
                      dcc_abbreviation = id_abbreviation,
                      dcc_description = id_description,
                      contact_email = contact_email,
                      contact_name = contact_name,
                      dcc_url = id_namespace,
                      project_id_namespace = project_id_namespace,
                      project_local_id = project_local_id)
dcc.tsv


project_cols <- getcolnames("osfstorage-archive/project.tsv")
project_cols

project.tsv <- data.frame(id_namespace = project_id_namespace,
                          local_id = project_local_id,
                          persistent_id = NA,
                          creation_time = "2017-11-06",
                          abbreviation = "NCBI",
                          name = "NCBI GEO",
                          description = "Repostitory for Gene Expression Data")
project.tsv

biosample_cols <- getcolnames("osfstorage-archive/biosample.tsv") 
biosample_cols


biosample.tsv <- data.frame(id_namespace = "https://www.ncbi.nlm.nih.gov/sra/",
                            local = "SRX",
                            id = 3368300:3368315,
                            project_id_namespace = project_id_namespace,
                            project_local_id = project_local_id, 
                            persistent_id = NA,
                            creation_time = "2017-11-06",
                            assay_type = "OBI:0002571",
                            anatomy = "UBERON:0003881") %>%
  mutate(local_id = paste(local, id, sep = "")) %>%
  select(all_of(biosample_cols))
biosample.tsv


biosample_gene_cols <- getcolnames("osfstorage-archive/biosample_gene.tsv") 
biosample_gene_cols


biosample_gene.tsv <- biosample.tsv %>%
  mutate(gene =  "ENSG00000102081") %>%
  dplyr::rename(biosample_id_namespace = id_namespace,
                biosample_local_id = local_id) %>%
  dplyr::select(all_of(biosample_gene_cols))
biosample_gene.tsv

id_namespace_cols <- getcolnames("osfstorage-archive/id_namespace.tsv")
id_namespace_cols

biosamplerow <- c("https://www.ncbi.nlm.nih.gov/sra/", "SRA", "SRA", "Sequence Read Archive", "")
biosamplerow 
  
id_namespace.tsv <- data.frame(id = id_namespace,
                               abbreviation = id_abbreviation,
                               name = id_name,
                               description = id_description) %>%
  rbind(., biosamplerow)
id_namespace.tsv


# unused
# granularity: 0" 
# "NCBI:txid10090" 


###################################################################

# save files

savefiles <- function(object){
  print(paste("Writing", substitute(object), "to file", sep = " "))
  write.table(object, file = paste0(outdir, substitute(object), sep = ""),
              sep ="\t", row.names = F, col.names = T, quote = F, na = "")
}

savefiles(dcc.tsv)
savefiles(id_namespace.tsv)
savefiles(project.tsv)

savefiles(biosample.tsv)
savefiles(biosample_gene.tsv)

# scp tsv files to FARM  
# follow https://github.com/nih-cfde/published-documentation/wiki/submission-prep-script
# run python prepare_C2M2_submission.py 
# scp autogenerated tsv files from FARM
# activate cfde-env
# CFDE_SUBMIT_SERVICE_INSTANCE=dev
# cfde-submit run rmh_2022_04_11 --dcc-id test1