curl -L https://osf.io/aef7g/download > compound.tsv.gz
curl -L https://osf.io/msfrq/download > doid.version_2021-10-12.obo
curl -L https://osf.io/nq6u9/download > EDAM.version_1.25.tsv
curl -L https://osf.io/5sxvt/download > ensembl_genes.tsv
curl -L https://osf.io/wcvuy/download > ensembl_organism_name_to_ncbi_taxonomy_id.tsv
curl -L https://osf.io/wcvuy/download > ensembl_organism_name_to_ncbi_taxonomy_id.tsv
curl -L https://osf.io/3k9e7/download > hp.2022-02-14.obo
curl -L https://osf.io/rq6au/download > hp.phenotype_to_genes.txt
curl -L https://osf.io/trewg/download > ncbi_taxonomy.tsv.gz
curl -L https://osf.io/76jnk/download > OBI.provisional_terms.2022-01-06.tsv
curl -L https://osf.io/mv4by/download > OBI.version_2021-08-18.obo